sudo: required
services:
  - docker

before_install:
  - docker build -t gbamparop/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true gbamparop/react-test npm test

after_success:
  - docker build -t gbamparop/multi-nginx ./nginx
  - docker build -t gbamparop/multi-server ./server
  - docker build -t gbamparop/multi-worker ./worker
  - docker build -t gbamparop/multi-client ./client
  # Log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Push images to docker hub
  - docker push gbamparop/multi-nginx
  - docker push gbamparop/multi-server
  - docker push gbamparop/multi-worker
  - docker push gbamparop/multi-client